import { Inter } from "next/font/google";
import "./globals.css";
import MyNavbar from "./StaticComponents/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "./StaticComponents/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#ebeded]">
        <MyNavbar/>
        {children}
        <Footer/></body>
    </html>
  );
}
